version: 2.1
executors:
  default:
    docker:
      - image: cimg/ruby:3.0.2
        environment:
            RAILS_ENV: test
            BUNDLE_PATH: vendor/bundle
            DATABASE_URL: postgres://postgres:@localhost:5432/circle_test
      - image: postgres:9.6.2-alpine
jobs:
  rspec:
    executor: default
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install
      - run: bundle install -j$(nproc)
      - run: bundle exec rake db:create db:migrate
      - run:
          command: bundle exec rspec
workflows:
  version: 2
  main:
    jobs:
      - rspec